// Build a Markdown report from the current diagnostics + source code.
// Designed to be paste-ready into Stack Overflow, Discord, GitHub issues,
// or class submissions.

const PASTE_PREVIEW_LINES = 2 // lines of context shown before each error

export function buildMarkdownReport({ language, code, diagnostics }) {
  const lines = code.split('\n')
  const ts    = new Date().toISOString()

  const header = [
    `# Syntax Inspector report`,
    `_Language: **${language}** · ${diagnostics.length} ${diagnostics.length === 1 ? 'issue' : 'issues'} · ${ts}_`,
    '',
  ]

  if (diagnostics.length === 0) {
    return [
      ...header,
      `No syntax errors found.`,
      '',
      `## Source`,
      '```' + language,
      code,
      '```',
      '',
    ].join('\n')
  }

  const issues = diagnostics.map((d, i) => {
    const num = String(i + 1).padStart(2, '0')
    const ctxStart = Math.max(0, (d.line ?? 1) - 1 - PASTE_PREVIEW_LINES)
    const ctxLines = lines.slice(ctxStart, (d.line ?? 1)).map((line, idx) => {
      const lineNo = ctxStart + idx + 1
      const marker = lineNo === d.line ? '→ ' : '  '
      return `${marker}${String(lineNo).padStart(4)}  ${line}`
    }).join('\n')

    return [
      `### ${num} · Line ${d.line}, Col ${(d.column ?? 0) + 1}`,
      `**${d.message}**`,
      '',
      '```',
      ctxLines,
      '```',
    ].join('\n')
  }).join('\n\n')

  const footer = [
    '',
    `## Full source`,
    '```' + language,
    code,
    '```',
    '',
    `_Generated by [Syntax Inspector](https://visaug36.github.io/syntax-inspector/)_`,
    '',
  ]

  return [...header, issues, ...footer].join('\n')
}

/** Trigger a browser file download with the given text content. */
export function downloadText(filename, text, mime = 'text/markdown') {
  const blob = new Blob([text], { type: mime + ';charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  // Free the blob in the next tick
  setTimeout(() => URL.revokeObjectURL(url), 0)
}
